{% set name = "cmdstan" %}
{% set version = "2.35.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz  # [x86 or arm64]
  sha256: 5bf668994e163419123d22bb7248ef1d30cbe2e7a14d50aa1c282b961f8172cd  # [x86 or arm64]
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 87ea47f0576d581f0af7e3c1a2f9843d16a9c7b21ed94621c906f7a3183b410d  # [aarch64]
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-linux-ppc64el.tar.gz  # [ppc64le]
  sha256: b36fcd962269759b5cef51da9585ceb73e7bea28d73f5eba00afdb1022f69cb0  # [ppc64le]

build:
  skip: True  # [not win]
  number: 1
  binary_relocation: false

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ posix }}make
    - {{ posix }}filesystem                # [win]
    - {{ posix }}sed                       # [win]
    - {{ posix }}coreutils                 # [win]
  host:
    - tbb-devel
  run:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ posix }}make
    - tbb-devel
    - {{ posix }}filesystem                # [win]
    - {{ posix }}sed                       # [win]
    - {{ posix }}coreutils                 # [win]
    - gxx_{{ target_platform }} >={{ cxx_compiler_version }}  # [linux]


# test:
#   downstreams:
#     - cmdstanpy

about:
  home: https://mc-stan.org/users/interfaces/cmdstan.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CmdStan, the command line interface to Stan
  description: |
    <b>CmdStan</b> is the command line interface to Stan, a package providing

    * full Bayesian inference using the No-U-Turn sampler (NUTS), a variant of Hamiltonian Monte Carlo (HMC),
    * penalized maximum likelihood estimation (MLE) using optimization, either Newton or quasi-Newton algorithms BFGS and L-BFGS,
    * approximate Bayesian inference using automatic differentiation variational inference (ADVI),
    * a full first- and higher-order automatic differentiation library based on C++ template overloads, and
    * a supporting fully-templated matrix, linear algebra, and probability special function library.
  doc_url: https://mc-stan.org/docs/cmdstan-guide/index.html
  dev_url: https://github.com/stan-dev/cmdstan

extra:
  recipe-maintainers:
    - maresb
    - WardBrian
