{% set name = "cmdstan" %}
{% set version = "2.29.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz  # [x86 or arm64]
  sha256: 567b531fa73ffdf706caa17eb3344e1dfb41e86993caf8ba40875ff910335153  # [x86 or arm64]
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 9b7eec78e217cab39d3d794e817a1ca08f36b1e5cb434c4cd8263bb2650ba125  # [aarch64]
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-linux-ppc64el.tar.gz  # [ppc64le]
  sha256: 5ad22765e04060c651a1e248513979a5ed12d75c782e6c3809cfe511526a06d3  # [ppc64le]
  patches:
    - no-dtag-flag.patch  # [osx]

build:
  number: 0
  binary_relocation: false

requirements:
  build:
    - {{ compiler('cxx') }}        # [not win]
    - make                         # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - m2w64-make                   # [win]
    - m2-filesystem                # [win]
    - m2-sed                       # [win]
    - m2-coreutils                 # [win]
  host:
    - tbb-devel                    # [not win]
  run:
    - {{ compiler('cxx') }}        # [not win]
    - make                         # [not win]
    - tbb-devel                    # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - m2w64-make                   # [win]
    - m2-filesystem                # [win]
    - m2-sed                       # [win]
    - m2-coreutils                 # [win]
  run_constrained:
    - tbb >=2021                   # [win]

test:
  downstreams:
    - cmdstanpy

about:
  home: https://mc-stan.org/users/interfaces/cmdstan.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CmdStan, the command line interface to Stan
  description: |
    <b>CmdStan</b> is the command line interface to Stan, a package providing

    * full Bayesian inference using the No-U-Turn sampler (NUTS), a variant of Hamiltonian Monte Carlo (HMC),
    * penalized maximum likelihood estimation (MLE) using optimization, either Newton or quasi-Newton algorithms BFGS and L-BFGS,
    * approximate Bayesian inference using automatic differentiation variational inference (ADVI),
    * a full first- and higher-order automatic differentiation library based on C++ template overloads, and
    * a supporting fully-templated matrix, linear algebra, and probability special function library.
  doc_url: https://mc-stan.org/docs/cmdstan-guide/index.html
  dev_url: https://github.com/stan-dev/cmdstan

extra:
  recipe-maintainers:
    - maresb
    - WardBrian
