{% set name = "cmdstan" %}
{% set version = "2.37.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz  # [x86 or arm64]
  sha256: 635e2e1cf9c4774c9019001325354d3610bae2adc4ed5af2fed87872dfc671fc  # [x86 or arm64]
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 7e979a4f088aab64b19af271bd0b76a4ad81b6cccd61f805154570c5a2624275  # [aarch64]
  url: https://github.com/stan-dev/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}-linux-ppc64el.tar.gz  # [ppc64le]
  sha256: 29f3f62673957bd5e001c9df9afd209eb1c4f7a2322abba89f45397547f34555  # [ppc64le]

build:
  number: 0
  binary_relocation: false

requirements:
  build:
    - {{ compiler('cxx') }}        # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}make
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - m2_conda_epoch == 20230914-0_x86_64  # [win]
  host:
    - tbb-devel                    # [not win]
  run:
    - {{ compiler('cxx') }}        # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}make
    - tbb-devel                    # [not win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - m2_conda_epoch == 20230914-0_x86_64  # [win]
    - gxx_{{ target_platform }} >={{ cxx_compiler_version }}  # [linux]
  run_constrained:
    - tbb >=2021                   # [win]

test:
  downstreams:
    - cmdstanpy
    - r-cmdstanr                   # [not win]

about:
  home: https://mc-stan.org/users/interfaces/cmdstan.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: CmdStan, the command line interface to Stan
  description: |
    <b>CmdStan</b> is the command line interface to Stan, a package providing

    * full Bayesian inference using the No-U-Turn sampler (NUTS), a variant of Hamiltonian Monte Carlo (HMC),
    * penalized maximum likelihood estimation (MLE) using optimization, either Newton or quasi-Newton algorithms BFGS and L-BFGS,
    * approximate Bayesian inference using automatic differentiation variational inference (ADVI),
    * a full first- and higher-order automatic differentiation library based on C++ template overloads, and
    * a supporting fully-templated matrix, linear algebra, and probability special function library.
  doc_url: https://mc-stan.org/docs/cmdstan-guide/index.html
  dev_url: https://github.com/stan-dev/cmdstan

extra:
  recipe-maintainers:
    - maresb
    - WardBrian
