build_platform:
  osx_arm64: osx_64
build_with_mambabuild: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
linux_aarch64:
  enabled: true
linux_ppc64le:
  enabled: true
provider:
  linux_aarch64: default
  linux_ppc64le: default
test_on_native_only: true
conda_build:
  pkg_format: '2'
