conda_forge_output_validation: true
linux_aarch64:
  enabled: true
linux_ppc64le:
  enabled: true
osx_arm64:
  enabled: true
provider:
  linux_aarch64: default
  linux_ppc64le: default
test_on_native_only: true
build_with_mambabuild: false
github:
  branch_name: main
  tooling_branch_name: main
